apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webhook-adapter.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "webhook-adapter.name" . }}
    helm.sh/chart: {{ include "webhook-adapter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  thehive-apikey: {{ .Values.thehive.apikey | b64enc | quote }}
