apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "cortex.name" . }}
    helm.sh/chart: {{ include "cortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application.conf: |
    play.http.secret.key="{{ .Values.application.secret }}"

    {{- if .Values.search.acceptAnyCertificate }}
    // Bypass SSL certificate validation for the Wazuh indexer (lab/dev only)
    play.ws.ssl.loose.acceptAnyCertificate = true
    {{- end }}

    search {
      index = cortex
      uri = "{{ if .Values.elasticsearch.ssl }}https{{ else }}http{{ end }}://{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
      {{- if .Values.elasticsearch.username }}
      username = "{{ .Values.elasticsearch.username }}"
      password = "{{ .Values.elasticsearch.password }}"
      {{- end }}
      trust-all = true
    }

    analyzer {
      urls = [
        "{{ .Values.analyzers.path }}"
      ]
    }

    responder {
      urls = [
        "{{ .Values.analyzers.respondersPath }}"
      ]
    }
