apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cortex.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "cortex.name" . }}
    helm.sh/chart: {{ include "cortex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  application-secret: {{ .Values.application.secret | b64enc | quote }}
  {{- if .Values.elasticsearch.password }}
  elasticsearch-password: {{ .Values.elasticsearch.password | b64enc | quote }}
  {{- end }}
